package game

// The 20x20 map every test but the AI's is written against. It used to be
// what the game itself ran on, so a pile of tests hardcode coordinates
// into it — the lake, the cliff and the two ore fields are all load-
// bearing for something. Keeping it as an explicit fixture means the real
// maps can change size and shape without dragging those tests along.
//
// Same notation as maps.go: first line is the top of the map.
const fixtureLayout = `
....................
....................
....................
====================
..............#.....
..............#.....
..............#.....
..............#.....
....~~~~~~....#.....
....~~~~~~....#.....
....~~~~~~....#.....
....~~~~~~....#.....
....~~~~~~....#.....
....~~~~~~....#..*..
..............#.....
..............#.....
..............#.....
.......*......#.....
....................
....................`

func newFixtureMap() *GameMap { return parseMap(fixtureLayout) }
