package game

import (
	"sort"
	"strings"
)

// maps.go holds the playable maps as ASCII art. A 40x40 map built by
// nested loops is unreadable — the old 20x20 one already was — and worse,
// the loops and the starting positions in NewWorld were two separate
// pieces of hardcoding that had to be kept in step by hand. Here the
// terrain, the ore drills and both starting positions are one artefact,
// and editing a map means editing a picture.
//
// One character per cell:
//
//	.  grass                =  road (passable, cosmetic)
//	~  water (impassable)   #  cliff (impassable)
//	*  ore drill — impassable, and ore grows in the cells around it
//	1  player 1's Construction Yard corner (the ground under it is grass)
//	2  player 2's
//
// The first line of a layout is the *top* of the map, so what you read is
// what you'd see looking down at it. Rows are flipped on parse, since the
// world's y grows upward.
//
// Both maps are rotationally symmetric: whatever is around one start is
// around the other, turned 180°. Anything else would hand one seat an
// advantage that has nothing to do with play.

// MapDefinition is one map as the lobby sees it.
type MapDefinition struct {
	Name  string
	Label string
}

var mapDefinitions = []MapDefinition{
	{Name: "crossroads", Label: "Crossroads"},
	{Name: "ridge", Label: "Ridge"},
}

var mapLayouts = map[string]string{
	"crossroads": mapCrossroads,
	"ridge":      mapRidge,
}

// DefaultMapName is what a room falls back to when it names a map that
// doesn't exist — a room with no map is not a thing that can start.
const DefaultMapName = "crossroads"

// MapCatalog lists the maps a room can be created on, in a stable order.
func MapCatalog() []MapDefinition {
	out := append([]MapDefinition(nil), mapDefinitions...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func ValidMapName(name string) bool {
	_, ok := mapLayouts[name]
	return ok
}

// NewMap builds the named map, falling back to the default rather than
// returning nil: every caller of this is starting a match, and none of
// them has anything useful to do with an error.
func NewMap(name string) *GameMap {
	layout, ok := mapLayouts[name]
	if !ok {
		layout = mapLayouts[DefaultMapName]
	}
	return parseMap(layout)
}

// parseMap turns a layout into terrain, ore fields and starting
// positions. Drills are planted after the terrain is down, because
// addOreDrill only spreads ore over plain grass — it has to be able to
// see what's already there.
func parseMap(layout string) *GameMap {
	rows := strings.Split(strings.TrimSpace(layout), "\n")

	height := len(rows)
	width := 0
	for _, row := range rows {
		row = strings.TrimSpace(row)
		if len(row) > width {
			width = len(row)
		}
	}

	m := &GameMap{Width: width, Height: height, Tiles: make([][]Tile, height), starts: map[int]cell{}}
	for y := range m.Tiles {
		m.Tiles[y] = make([]Tile, width)
		for x := range m.Tiles[y] {
			m.Tiles[y][x] = Tile{Type: Grass, Passable: true}
		}
	}

	var drills []cell

	for i, row := range rows {
		// The literal reads top-down; the world counts y upward.
		y := height - 1 - i
		for x, ch := range strings.TrimSpace(row) {
			switch ch {
			case '=':
				m.Tiles[y][x] = Tile{Type: Road, Passable: true}
			case '~':
				m.Tiles[y][x] = Tile{Type: Water, Passable: false}
			case '#':
				m.Tiles[y][x] = Tile{Type: Cliff, Passable: false}
			case '*':
				drills = append(drills, cell{X: x, Y: y})
			case '1', '2':
				m.starts[int(ch-'0')] = cell{X: x, Y: y}
			}
		}
	}

	for _, d := range drills {
		m.addOreDrill(d, oreFieldRadius)
	}
	return m
}

// Start is where a player's Construction Yard goes — the corner of its
// footprint, not its centre.
func (m *GameMap) Start(player int) (cell, bool) {
	c, ok := m.starts[player]
	return c, ok
}

// StartCount is how many seats the map has room for.
func (m *GameMap) StartCount() int { return len(m.starts) }

const mapCrossroads = `
........................................
...................==...................
...................==...................
...................==...................
...................==...................
...................==.............2.....
...................==....########.......
...................==...................
...................*=...................
.............~.....==...................
..........~~~~~~~..==...................
........~~~~~~~~~~~==...................
........~~~~~~~~~~~==...................
.......~~~~~~~~~~~~==...................
........~~~~~~~~~~~==............*......
........~~~~~~~~~~~==...................
..........~~~~~~~..==...................
.............~.....==...................
...................==...................
.======================================.
.======================================.
...................==...................
...................==.....~.............
...................==..~~~~~~~..........
...................==~~~~~~~~~~~........
......*............==~~~~~~~~~~~........
...................==~~~~~~~~~~~~.......
...................==~~~~~~~~~~~........
...................==~~~~~~~~~~~........
...................==..~~~~~~~..........
...................==.....~.............
...................=*...................
...................==...................
.......########....==...................
...................==...................
...................==...................
...1...............==...................
...................==...................
...................==...................
........................................`

const mapRidge = `
...................##...................
...................##...................
...................##...................
...................##...................
........~..........##...................
.....~~~~~~~.......##...................
....~~~~~~~~~......##...................
...~~~~~~~~~~~.....##...................
....~~~~~~~~~......##...................
.....~~~~~~~.......##...................
........~...............................
........................................
.======================================.
................*.......................
........................................
...................##...................
...................##...................
...................##......*............
...................##...................
........*..........##...................
...................##..........*..2.....
...1...............##...................
............*......##...................
...................##...................
...................##...................
........................................
.......................*................
.======================================.
........................................
...............................~........
...................##.......~~~~~~~.....
...................##......~~~~~~~~~....
...................##.....~~~~~~~~~~~...
...................##......~~~~~~~~~....
...................##.......~~~~~~~.....
...................##..........~........
...................##...................
...................##...................
...................##...................
...................##...................`
